In [4]:
import os
import pandas as pd
from tqdm import tqdm

In [77]:
input_path = '/media/kovan_ai_tor_the_beast/hard_drive_1/DATA/amino_acid_tags/'

In [60]:
main_record = []
for root, dirs, files in os.walk(source_path, topdown=False): # See below for details of source path
    for name in tqdm(files):
        main_record.append(name.split('_')[0])
print(len(main_record))

100%|██████████| 145103/145103 [00:00<00:00, 1941828.97it/s]

145103


In [78]:
# General Statistics on Entire PDB Population
size = []
zeros = []
for root, dirs, files in os.walk(input_path, topdown=False):
    for name in tqdm(files):
        with open(input_path + name) as f:
            count = sum(1 for line in f)
            if count != 0:
                size.append(count)
            else:
                 zeros.append(name.split('_')[0])

100%|██████████| 149271/149271 [00:11<00:00, 12708.10it/s]


In [79]:
print(len(size))
print(len(zeros))
print(len(size) - len(zeros))

148821
450
148371


In [10]:
df = pd.DataFrame(data=size, columns=['length'])

In [11]:
print(df.head())
print(df.shape)
print(df.describe())

   length
0     696
1    1737
2     137
3     702
4     427
(148821, 1)
              length
count  148821.000000
mean      917.211758
std      2514.449808
min         1.000000
25%       271.000000
50%       473.000000
75%       924.000000
max    357168.000000


In [80]:
# Create dataset of proteins < 300 amino acids in length for message-parsing neural network
counter = []
tag = []
for root, dirs, files in os.walk(input_path, topdown=False):
    for name in tqdm(files):
        if name.split('_')[0] in main_record:
            with open(input_path + name) as f:
                count2 = sum(1 for line in f)
                if count2 != 0:
                    if len(counter) > 99:
                        break
                    else:
                        if count2 <= 300:
                            counter.append(count2)
                            tag.append(name.split('_')[0])
                            print("{} {}".format(name.split('_')[0], count2))

  0%|          | 181/149271 [00:00<02:45, 899.17it/s]

6ajw 137
1foy 76
4jyq 291
5fc4 144
1kok 294
4gv5 127
5nvb 300
2yv7 235
2rb8 93
5i12 162
3n38 290
1p4b 234
3uaf 117
4tt6 132
1rc4 159
5zrp 132
4h55 233
1i5r 285
3tof 202
1kwj 68
4p9v 102
5jdm 296
2q1m 119
4m7i 247
5cn3 237
3cfm 253
4nqu 208
3dju 121
3bii 222
4fob 295
4n6q 178
1yzk 168
1tj4 244
4qxo 186
1gjn 153
1dfu 94
1kvy 123
1eos 248
5i5n 272
1a6g 153
6gnc 288
1kve 280
4go5 167
1kc3 299
2mie 120
4ifn 285
2p7s 113
2fbd 245
3bgp 272
3f9e 297
5efm 16
6ohk 172
3sa4 206
1ix4 212
2r48 105


  0%|          | 361/149271 [00:00<02:42, 914.09it/s]

4c44 150
6gjl 172
5o7r 193
1b4l 153
2pry 215
3mo9 266
4c9g 265
2ler 220
5m9y 140
3c5l 221
6gr4 227
2bd8 241
1b6j 198
1kn5 102
5xuq 241
5puu 255
5cfe 252
5psj 255
2hip 142
5fnd 209
1ub0 246
3cri 283
2lr2 152
6eik 214
4zj2 270
3uec 141
2zo0 210
3q3j 278
6gpd 254
1bic 258
3lru 300
1p1n 258
6gd6 129
2r4x 290
1ek3 228
4fxc 98
1epi 53
5b4i 260
1uak 243
5iph 170
3ret 188
5usv 51
5j0m 130
1aal 115
5tzp 167


In [81]:
print(counter)
print(tag)
print(len(counter))
print(len(tag))

[137, 76, 291, 144, 294, 127, 300, 235, 93, 162, 290, 234, 117, 132, 159, 132, 233, 285, 202, 68, 102, 296, 119, 247, 237, 253, 208, 121, 222, 295, 178, 168, 244, 186, 153, 94, 123, 248, 272, 153, 288, 280, 167, 299, 120, 285, 113, 245, 272, 297, 16, 172, 206, 212, 105, 150, 172, 193, 153, 215, 266, 265, 220, 140, 221, 227, 241, 198, 102, 241, 255, 252, 255, 142, 209, 246, 283, 152, 214, 270, 141, 210, 278, 254, 258, 300, 258, 129, 290, 228, 98, 53, 260, 243, 170, 188, 51, 130, 115, 167]
['6ajw', '1foy', '4jyq', '5fc4', '1kok', '4gv5', '5nvb', '2yv7', '2rb8', '5i12', '3n38', '1p4b', '3uaf', '4tt6', '1rc4', '5zrp', '4h55', '1i5r', '3tof', '1kwj', '4p9v', '5jdm', '2q1m', '4m7i', '5cn3', '3cfm', '4nqu', '3dju', '3bii', '4fob', '4n6q', '1yzk', '1tj4', '4qxo', '1gjn', '1dfu', '1kvy', '1eos', '5i5n', '1a6g', '6gnc', '1kve', '4go5', '1kc3', '2mie', '4ifn', '2p7s', '2fbd', '3bgp', '3f9e', '5efm', '6ohk', '3sa4', '1ix4', '2r48', '4c44', '6gjl', '5o7r', '1b4l', '2pry', '3mo9', '4c9g', '2ler', '5

In [82]:
df2 = pd.DataFrame(data=counter, columns=['length'])
df3 = pd.DataFrame(data=tag, columns=['name'])
df4 = pd.concat([df3, df2], axis=1)
print(df4.head())
print(df4.shape)
print(df4['length'].describe())

   name  length
0  6ajw     137
1  1foy      76
2  4jyq     291
3  5fc4     144
4  1kok     294
(100, 2)
count    100.000000
mean     198.100000
std       70.117578
min       16.000000
25%      140.750000
50%      209.500000
75%      255.000000
max      300.000000
Name: length, dtype: float64


In [83]:
print(tag)

['6ajw', '1foy', '4jyq', '5fc4', '1kok', '4gv5', '5nvb', '2yv7', '2rb8', '5i12', '3n38', '1p4b', '3uaf', '4tt6', '1rc4', '5zrp', '4h55', '1i5r', '3tof', '1kwj', '4p9v', '5jdm', '2q1m', '4m7i', '5cn3', '3cfm', '4nqu', '3dju', '3bii', '4fob', '4n6q', '1yzk', '1tj4', '4qxo', '1gjn', '1dfu', '1kvy', '1eos', '5i5n', '1a6g', '6gnc', '1kve', '4go5', '1kc3', '2mie', '4ifn', '2p7s', '2fbd', '3bgp', '3f9e', '5efm', '6ohk', '3sa4', '1ix4', '2r48', '4c44', '6gjl', '5o7r', '1b4l', '2pry', '3mo9', '4c9g', '2ler', '5m9y', '3c5l', '6gr4', '2bd8', '1b6j', '1kn5', '5xuq', '5puu', '5cfe', '5psj', '2hip', '5fnd', '1ub0', '3cri', '2lr2', '6eik', '4zj2', '3uec', '2zo0', '3q3j', '6gpd', '1bic', '3lru', '1p1n', '6gd6', '2r4x', '1ek3', '4fxc', '1epi', '5b4i', '1uak', '5iph', '3ret', '5usv', '5j0m', '1aal', '5tzp']


In [49]:
import shutil 

## Move amino acid test dataset tags to TEST_DATA

destination_path = '/media/kovan_ai_tor_the_beast/hard_drive_2/TEST_DATA/tags/'

In [84]:
for t in tag:
    shutil.copy(input_path + t + '_amino_acid_tag_.csv', destination_path)

## Move adjacency matrix test dataset to TEST_DATA

In [68]:
source_path = '/media/kovan_ai_tor_the_beast/disk/protein_folding/pickle_files/pickle_label_gz/'
destination_path_2 = '/media/kovan_ai_tor_the_beast/hard_drive_2/TEST_DATA/adjacency/dataset_gz/'

In [86]:
for t in tag:
    shutil.copy(source_path + t + '_label.pickle.gz', destination_path_2)

In [2]:
# Investigate creation of different adjacency matricies - fully connected, direct neighbours only

In [2]:
import numpy as np

In [3]:
source_path_2 = '/media/kovan_ai_tor_the_beast/hard_drive_2/TEST_DATA/tags/'

In [4]:
counter = []
tag = []
for root, dirs, files in os.walk(source_path_2, topdown=False):
    for name in tqdm(files):
        with open(source_path_2 + name) as f:
            count2 = sum(1 for line in f)
            if count2 != 0:
                if len(counter) > 99:
                    break
                else:
                    if count2 <= 300:
                        counter.append(count2)
                        tag.append(name.split('_')[0])
                        print("{} {}".format(name.split('_')[0], count2))

100%|██████████| 100/100 [00:00<00:00, 5010.28it/s]

5xuq 241
4c44 150
1dfu 94
1i5r 285
2lr2 152
1ek3 228
1ix4 212
5efm 16
5i5n 272
5o7r 193
5b4i 260
1b6j 198
1kc3 299
4nqu 208
6eik 214
3sa4 206
4ifn 285
2zo0 210
1a6g 153
4m7i 247
4zj2 270
4fob 295
6gr4 227
1epi 53
3n38 290
5cn3 237
1yzk 168
2fbd 245
5puu 255
6gd6 129
3bgp 272
2mie 120
4tt6 132
5psj 255
2r48 105
3cfm 253
2p7s 113
1eos 248
4jyq 291
3tof 202
6ajw 137
5iph 170
1b4l 153
5tzp 167
1kvy 123
6ohk 172
5usv 51
5zrp 132
5j0m 130
1bic 258
3q3j 278
1rc4 159
6gpd 254
3bii 222
2pry 215
6gjl 172
2bd8 241
5nvb 300
5fc4 144
4go5 167
3lru 300
4fxc 98
1kve 280
1kok 294
5fnd 209
4gv5 127
1tj4 244
1kwj 68
1foy 76
3f9e 297
2yv7 235
2ler 220
1ub0 246
2hip 142
1uak 243
1aal 115
2r4x 290
3c5l 221
5jdm 296
4p9v 102
4h55 233
1p4b 234
1p1n 258
4c9g 265
5cfe 252
3ret 188
2rb8 93
3uaf 117
3dju 121
1kn5 102
1gjn 153
6gnc 288
5m9y 140
3cri 283
4n6q 178
3uec 141
3mo9 266
5i12 162
2q1m 119
4qxo 186


In [14]:
x = np.triu([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [16]:
y = np.zeros((3,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
z = np.add(x,y)
z = np.triu(z, k=1)
print(z)

[[0. 2. 3.]
 [0. 0. 6.]
 [0. 0. 0.]]


In [30]:
c = 10
x = np.zeros((c,c))
y = np.ones((c,c))
z = np.add(x,y)
z = np.triu(z, k=1)
print(z)

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [26]:
import torch

In [51]:
torch.cuda.empty_cache()
device = torch.device('cuda')
c = 10
#x = torch.zeros((c,c), device=device)
x = torch.eye(c, device=device)
y = torch.ones((c,c), device=device)
z = torch.sub(y,x)
#z = torch.triu(z, diagonal=1)
print(z)
print(z.shape)
#y = torch.flatten(y)
#print(y)
#print(y.shape)

tensor([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]], device='cuda:0')
torch.Size([10, 10])


In [ ]:
c = 10000
x = torch.zeros((c,c))
y = torch.ones((c,c))
z = torch.add(x,y)
z = torch.triu(z, diagonal=1)
print(z)

In [62]:
source = '/media/kovan_ai_tor_the_beast/hard_drive_2/TEST_DATA/adjacency/fully_connected/6ajw_fully_connected.pickle'

In [63]:
object = pd.read_pickle(source)

In [64]:
with open(source, 'rb') as labels_file:
    df = pd.read_pickle(labels_file)
print(df)

tensor([[0., 1., 1.,  ..., 1., 1., 1.],
        [1., 0., 1.,  ..., 1., 1., 1.],
        [1., 1., 0.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 0., 1., 1.],
        [1., 1., 1.,  ..., 1., 0., 1.],
        [1., 1., 1.,  ..., 1., 1., 0.]])


In [85]:
source3 = '/media/kovan_ai_tor_the_beast/hard_drive_2/TEST_DATA/adjacency/dataset_gz/4fob_label.pickle'

In [86]:
with open(source3, 'rb') as labels_file:
    df2 = pd.read_pickle(labels_file)
print(df2)

tensor([[ 0.0000,  3.8130,  6.3698,  ..., 51.6755, 54.5117, 54.1919],
        [ 3.8130,  0.0000,  3.8142,  ..., 49.5547, 52.4936, 52.4054],
        [ 6.3698,  3.8142,  0.0000,  ..., 49.2851, 52.3872, 52.4674],
        ...,
        [51.6755, 49.5547, 49.2851,  ...,  0.0000,  3.7926,  6.4889],
        [54.5117, 52.4936, 52.3872,  ...,  3.7926,  0.0000,  3.8312],
        [54.1919, 52.4054, 52.4674,  ...,  6.4889,  3.8312,  0.0000]],
       dtype=torch.float64)


In [88]:
z = torch.triu(df2, diagonal=1)
print(z)
print(z.shape)

tensor([[ 0.0000,  3.8130,  6.3698,  ..., 51.6755, 54.5117, 54.1919],
        [ 0.0000,  0.0000,  3.8142,  ..., 49.5547, 52.4936, 52.4054],
        [ 0.0000,  0.0000,  0.0000,  ..., 49.2851, 52.3872, 52.4674],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  3.7926,  6.4889],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  3.8312],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
       dtype=torch.float64)
torch.Size([295, 295])


In [89]:
295**2

87025

In [90]:
a = torch.flatten(z)
print(a)
print(a.shape)

tensor([0.0000, 3.8130, 6.3698,  ..., 0.0000, 0.0000, 0.0000],
       dtype=torch.float64)
torch.Size([87025])


In [91]:
source4 = '/media/kovan_ai_tor_the_beast/hard_drive_2/TEST_DATA/adjacency/distance/3ret_distance_label.pickle'

In [92]:
with open(source4, 'rb') as labels_file:
    df4 = pd.read_pickle(labels_file)
print(df4)
print(df4.shape)

tensor([0.0000, 3.7812, 6.7638,  ..., 0.0000, 0.0000, 0.0000],
       dtype=torch.float64)
torch.Size([35344])
