In [1]:
import pickle
import torch

### Check data format

In [11]:
source1 = '/media/the_beast/A/mathisi_tests/data/transformed/testset/direct_neighbour/3a4r_adjacency-matrix.pickle'

In [12]:
with open(source1, 'rb') as labels_file:
    df1 = pickle.load(labels_file)
print(df1)
print(df1.shape)

tensor([[0., 1., 0.,  ..., 0., 0., 0.],
        [1., 0., 1.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 1., 0., 1.],
        [0., 0., 0.,  ..., 0., 1., 0.]])
torch.Size([300, 300])


In [13]:
source2 = '/media/the_beast/A/mathisi_tests/data/transformed/testset/direct_neighbour/3a4r_features.pickle'

In [14]:
with open(source2, 'rb') as labels_file:
    df2 = pickle.load(labels_file)
print(df2)
print(df2.shape)

tensor([[0.0000, 1.0000, 0.0000,  ..., 0.0000, 0.1304, 0.4674],
        [1.0000, 0.0000, 0.0000,  ..., 0.0704, 1.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.6294, 0.3847, 0.7627],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
       dtype=torch.float64)
torch.Size([300, 58])


In [15]:
source3 = '/media/the_beast/A/mathisi_tests/data/transformed/testset/direct_neighbour/3a4r_labels.pickle'

In [16]:
with open(source3, 'rb') as labels_file:
    df3 = pickle.load(labels_file)
print(df3)
print(df3.shape)

tensor([0.0121, 0.0177, 0.0181,  ..., 0.0000, 0.0000, 0.0000],
       dtype=torch.float64)
torch.Size([44850])


In [8]:
300*299/2

44850.0

### Check whether files are empty

In [ ]:
import os
import torch

In [ ]:
source_a = '/media/the_beast/A/mathisi_tests/data/testset/direct_neighbour/'

In [ ]:
for root, dirs, files in os.walk(source_a, topdown=False):
    for name in files:
        print(name.split('_')[0])
        with open(source_a + name, 'rb') as labels_file:
            df = pd.read_pickle(labels_file)
            print(f"Name: {name.split('_')[0]} and lenght of file: {df.shape}")

#### Check for NaN entries

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

In [ ]:
for root, dirs, files in os.walk(source_a, topdown=False):
    for name in files:
        if 'feature' in name:
            with open(source_a + name, 'rb') as labels_file:
                df = pd.read_pickle(labels_file).to(device)
                df_flat = torch.flatten(df)
                for i in df_flat.to(device):
                    if torch.isnan(i) == True:
                        print(f"Name: {name.split('_')[0]} contains NaN")

### Check same amino acids are in all three datatypes (adjacency matrix, features, labels)

In [ ]:
# source_a = '/media/the_beast/A/mathisi_tests/data/nearest_neighbour_8_normalised/'
tag_list = []
tag_list.clear()
for root, dirs, files in os.walk(source_a, topdown=False):
    for name in files:
        tag_list.append(name.split('_')[0])
print(tag_list)
print(len(tag_list))

In [ ]:
tag_counter = {}
for tag in tag_list:
    tag_count = tag_list.count(tag)
    tag_counter.update({tag:tag_count})

In [ ]:
# print(tag_counter)

In [ ]:
key_list = []
key_list.clear()
for key, value in tag_counter.items():
    if value != 3:
        key_list.append(key)
print(key_list)

In [ ]:
file_path = '/media/the_beast/A/mathisi_tests/data/sample_100/test_data/'
for root, dirs, files in os.walk(source_a, topdown=False):
    for name in files:
        if name.split('_')[0] in key_list:
            try:
                os.remove(file_path + name.split('_')[0] + '_adjacency-matrix.pickle')
            except:
                pass
            try:
                os.remove(file_path + name.split('_')[0] + '_features.pickle')
            except:
                pass
            try:
                os.remove(file_path + name.split('_')[0] + '_labels.pickle')
            except:
                pass

### Check whether data contains negative values

In [ ]:
source_b = '/media/the_beast/A/mathisi_tests/data/nearest_neighbour_4_normalised/'

In [ ]:
for root, dirs, files in os.walk(source_b, topdown=False):
    for name in files:
        if 'label' in name:
            with open(source_b + name, 'rb') as labels_file:
                df = pd.read_pickle(labels_file).to(device)
                for i in df.to(device):
                    if i < 0:
                        print(i)

In [ ]:
source2 = '/media/the_beast/A/mathisi_tests/data/LSTM/data/1a5y_labels.pickle'

In [ ]:
with open(source2, 'rb') as labels_file:
    df2 = pd.read_pickle(labels_file)
    for i in df2:
        print(i)

In [ ]:
x = torch.tensor([1, 2, np.nan])
for i in x:
    if torch.isnan(i) == True:
        print(f"Contains NaN")

In [ ]:
source2 = '/media/the_beast/A/mathisi_tests/data/LSTM/data/1a5y_labels.pickle'

In [ ]:
with open(source2, 'rb') as labels_file:
    df2 = pd.read_pickle(labels_file)
#print(df2)
print(df2.shape)

In [ ]:
import os

In [ ]:
source = '/media/the_beast/A/mathisi_tests/data/LSTM/data/'

In [ ]:
for root, dirs, files in os.walk(source, topdown=False):
    for name in files:
        if 'features' in name:
            with open(source + name, 'rb') as labels_file:
                df = pd.read_pickle(labels_file)
                print(f"Name: {name.split('_')[0]} and lenght of file: {df.shape}")

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader, random_split

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [ ]:
source4 = '/media/the_beast/A/mathisi_tests/data/LSTM/data/3zxo_features.pickle'

In [ ]:
with open(source4, 'rb') as labels_file:
    df4 = pd.read_pickle(labels_file)
print(df4)
print(df4.shape)

In [ ]:
from attention.protein_loader import ProteinLoader

x = ProteinLoader('/media/the_beast/A/mathisi_tests/data/LSTM/data/')
dataset = x.get_all_data()
batch_size = 5
n_workers = 1
validation_split = 0.01
shuffle = True

dataloader = DataLoader(dataset=dataset, batch_size=batch_size, shuffle=True, num_workers=n_workers)
print(f"dataset size: {len(dataset)} \ndataloader size: {len(dataloader)}")

In [ ]:
EPOCHS = batch_size
z = 0
for epoch in range(EPOCHS):
    print(f"Epoch number: {epoch+1}/{EPOCHS}")
    for idx, (inputs, targets) in enumerate(dataloader):
        z += 1
        print(z)
        print(targets[0][10])

In [ ]:
z = 0
num_epochs = 15
for epoch in range(num_epochs):
    print(f"Epoch: {epoch+1}/{num_epochs}")
    for idx, (data, targets) in enumerate(dataloader):
        data = data.to(device=device)
        targets = targets.to(device=device)
        z += 1
        print(z)
        print(data)
        print(targets)

In [ ]:
source1 = '/media/the_beast/disk/protein_folding/pickle_files/pickle_features_gz/101m_feature.pickle.gz'

In [ ]:
with gzip.open(source1) as f:
    features_train = pd.read_csv(f)

features_train.head()

### Get max distance value from all distance matricies 

In [6]:
import os
import torch
import tqdm

In [14]:
source = '/media/the_beast/A/mathisi_tests/data/distance_matrix/'

In [21]:
max_values = []
max_values.clear()
for root, dirs, files in os.walk(source, topdown=False):
    print(len(files))
    for file in files:
        with open(source + file, 'rb') as labels_file:
            try:
                tensor = pickle.load(labels_file)
                max_values.append(torch.max(tensor))
            except:
                pass
print(max_values)
print(len(max_values))

43225
[tensor(69.6342, dtype=torch.float64), tensor(55.0772, dtype=torch.float64), tensor(46.9815, dtype=torch.float64), tensor(39.4282, dtype=torch.float64), tensor(55.6138, dtype=torch.float64), tensor(90.3949, dtype=torch.float64), tensor(37.6440, dtype=torch.float64), tensor(44.6032, dtype=torch.float64), tensor(46.1613, dtype=torch.float64), tensor(46.5047, dtype=torch.float64), tensor(45.8760, dtype=torch.float64), tensor(67.8073, dtype=torch.float64), tensor(49.8936, dtype=torch.float64), tensor(66.1385, dtype=torch.float64), tensor(74.6887, dtype=torch.float64), tensor(46.4988, dtype=torch.float64), tensor(56.4796, dtype=torch.float64), tensor(72.3744, dtype=torch.float64), tensor(65.7980, dtype=torch.float64), tensor(34.8786, dtype=torch.float64), tensor(46.0122, dtype=torch.float64), tensor(60.3291, dtype=torch.float64), tensor(89.4611, dtype=torch.float64), tensor(50.5336, dtype=torch.float64), tensor(60.3742, dtype=torch.float64), tensor(52.6863, dtype=torch.float64), tenso

In [23]:
import pandas as pd

In [24]:
df_max_values = pd.DataFrame(max_values)
df_max_values.head()

0
0  69.634236
1  55.077181
2  46.981465
3  39.428187
4  55.613791

In [25]:
df_max_values.describe()

0
count  43167.000000
mean      53.418797
std       14.684946
min        0.000000
25%       44.917199
50%       52.908472
75%       59.852544
max      313.154920

In [26]:
53/313

0.16932907348242812

In [27]:
10/313

0.03194888178913738

In [28]:
1/313

0.003194888178913738

In [29]:
source8 = '/media/the_beast/A/mathisi_tests/data/distance_matrix/41bi_label.pickle'

In [30]:
with open(source8, 'rb') as labels_file:
    df8 = pickle.load(labels_file)
print(df8)

tensor([[ 0.0000,  3.7917,  6.6483,  ..., 18.0047, 18.4575, 17.5925],
        [ 3.7917,  0.0000,  3.8157,  ..., 14.5637, 15.2197, 14.4396],
        [ 6.6483,  3.8157,  0.0000,  ..., 11.4530, 11.9104, 11.5560],
        ...,
        [18.0047, 14.5637, 11.4530,  ...,  0.0000,  3.8024,  6.8247],
        [18.4575, 15.2197, 11.9104,  ...,  3.8024,  0.0000,  3.7835],
        [17.5925, 14.4396, 11.5560,  ...,  6.8247,  3.7835,  0.0000]],
       dtype=torch.float64)


In [31]:
df8/313

tensor([[0.0000, 0.0121, 0.0212,  ..., 0.0575, 0.0590, 0.0562],
        [0.0121, 0.0000, 0.0122,  ..., 0.0465, 0.0486, 0.0461],
        [0.0212, 0.0122, 0.0000,  ..., 0.0366, 0.0381, 0.0369],
        ...,
        [0.0575, 0.0465, 0.0366,  ..., 0.0000, 0.0121, 0.0218],
        [0.0590, 0.0486, 0.0381,  ..., 0.0121, 0.0000, 0.0121],
        [0.0562, 0.0461, 0.0369,  ..., 0.0218, 0.0121, 0.0000]],
       dtype=torch.float64)